"""empty message

Revision ID: 582eecd2af78
Revises: 2f7b70f6b7d7
Create Date: 2026-04-23 19:16:17.700098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582eecd2af78'
down_revision: Union[str, Sequence[str], None] = '2f7b70f6b7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pseudo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pseudo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
