"""sync user auth schema

Revision ID: 9b295feeb2b1
Revises: 582eecd2af78
Create Date: 2026-04-23 19:25:11.956293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b295feeb2b1'
down_revision: Union[str, Sequence[str], None] = '582eecd2af78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pseudo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pseudo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
